name: bco_app
description: "PCA Book of Church Order mobile reading app"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.0
  flutter_html: ^3.0.0-beta.2
  provider: ^6.1.0
  html: ^0.15.4
  url_launcher: ^6.2.0
  google_fonts: ^6.2.0
  pdfrx: ^1.0.0
  flutter_html_table: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bco_content/
    - assets/studies/
